### ISSUE TITLE
Nested parentheses

### ISSUE THREAD

**Issue by AntoineGagne** [Michaelt293/isotope#11]
I was trying out the library with GHCi but when I tried an expression with nested parentheses, it didn't seem to work. Here is the GHCi session:

```haskell
λ [mol|(((H2O)4)3)8|]

<interactive>:9:6:
    Could not parse formula: 1:2:
unexpected '('
expecting "Ag", "Al", "Ar", "As", "Au", "Ba", "Be", "Bi", "Br", "Ca", "Cd", "Ce", "Cl", "Co", "Cr", "Cs", "Cu", "Dy", "Er", "Eu", "Fe", "Ga", "Gd", "Ge", "He", "Hf", "Hg", "Ho", "In", "Ir", "Kr", "La", "Li", "Lu", "Mg", "Mn", "Mo", "Na", "Nb", "Nd", "Ne", "Ni", "Os", "Pa", "Pb", "Pd", "Pr", "Pt", "Rb", "Re", "Rh", "Ru", "Sb", "Sc", "Se", "Si", "Sm", "Sn", "Sr", "Ta", "Tb", "Te", "Th", "Ti", "Tl", "Tm", "Xe", "Yb", "Zn", "Zr", 'B', 'C', 'F', 'H', 'I', 'K', 'N', 'O', 'P', 'S', 'U', 'V', 'W', or 'Y'
```

Is it intended?

**Comment by Michaelt293** [comment]
I did intend to support the nesting of condensed formulae within condensed formulae. I had a few problems getting the parser to behave how I wanted so I went with a simpler solution which does not support the nesting like you have shown above.

If this nesting is useful to you, I will attempt to rewrite the parser to support this nesting.

edit: Just had a bit of a closer look. In Isotope, `CondensedFormula` is defined as

```
newtype CondensedFormula = CondensedFormula {
    getCondensedFormula :: [Either MolecularFormula ([MolecularFormula], Int)] }
        deriving (Show, Read, Eq, Ord)
```
This data type does not support nesting (for that `CondensedFormula` would need to be a recursive data type). To support nesting, quite a few things would need to be changed and I am not sure whether that is worth doing at this stage. Do you have any real examples where the lack of nesting is a problem? In the example you have given, it could be written as `(H2O)96` (I know it was just a simple example to show the problem).

**Comment by Michaelt293** [comment]
Turns out it was easier than I thought, checkout the branch `nested-forumulae`. 

The example you had can now be parsed -

```
ghci> [con|(((H2O)4)3)8|]
CondensedFormula {getCondensedFormula = [Right (CondensedFormula {getCondensedFormula = [Right (CondensedFormula {getCondensedFormula = [Right (CondensedFormula {getCondensedFormula = [Left (MolecularFormula {getMolecularFormula = fromList [(H,2)]}),Left (MolecularFormula {getMolecularFormula = fromList [(O,1)]})]},4)]},3)]},8)]}
```

I need to rewrite the generator for `CondensedFormula` for the tests to pass.

**Comment by Michaelt293** [comment]
See #12 - Looks good to go. I will recheck everything before merging the pull request.

@AntoineGagne if you want any input, it might be good to do so soon since I'll merge and close this issue in a couple of days time. Thanks for the suggestion!
